Repository RyanNgWH/WhichCard-backend, pull requests merged in 2023-07, with the labels that each got.

#11 Feature: Add merchant endpoints
  docs/card/createCard.md
  docs/merchant/createMerchant.md
  docs/merchant/deleteMerchantById.md
  docs/merchant/getAllActiveMerchants.md
  docs/merchant/getAllMerchants.md
  docs/merchant/getMerchantById.md
  docs/merchant/updateMerchantById.md
  index.ts
  src/controllers/merchantController.ts
  src/database/merchantDatabase.ts
  src/database/models/merchantModels.ts
  src/services/merchantService.ts
  src/shared/errors/database/merchant/merchantExistsError.ts
  src/shared/errors/database/merchant/merchantNotFoundError.ts
  src/shared/schemas/merchantSchemas.ts
  src/shared/types.ts
  src/v1/routes/merchantRoutes.ts
Labels: feature

#10 Add password hashing with SHA-256 algorithm.
  docs/user/addUserCard.md
  docs/user/createUser.md
  docs/user/getAllUsers.md
  docs/user/getUserbyId.md
  docs/user/login.md
  docs/user/updateUserById.md
  src/services/userService.ts
Labels: enhancement

#13 Feature: Implement card recommendation
  docs/user/deleteUserById.md
  docs/user/getAllUserCards.md
  docs/user/recommend.md
  src/controllers/userController.ts
  src/database/transactionDatabase.ts
  src/services/userService.ts
  src/shared/categories.ts
  src/shared/errors/user/noCardsError.ts
  src/v1/routes/userRoutes.ts
Labels: feature

#14 Feature: Add automated (integration) testing for user management endpoints
  app.ts
  docs/user/addUserCard.md
  docs/user/createUser.md
  docs/user/getUserCardByName.md
  example.env
  index.ts
  jest.config.js
  package-lock.json
  package.json
  src/database/cardDatabase.ts
  src/database/connection.ts
  src/shared/categories.ts
  tests/data/cards/cards.js
  tests/data/merchants/merchants.js
  tests/data/transactions/transactions.js
  tests/data/users/users.js
  tests/helpers.ts
  tests/integration/user.test.ts
  tests/integration/userCard.test.ts
Labels: feature

#18 Bugfix: Recommend card test case
  tests/integration/user.test.ts
Labels: bug
